### ISSUE TITLE
能否直接在文件夹或文件右键添加备注呢？

### ISSUE THREAD

**Issue by shaochangxing** [Link-Kou/intellij-treeInfotip#1]
手写xml感觉有点麻烦

**Comment by Link-Kou** [comment]
@shaochangxing  由于最早的设计目的是解决项目交接的时候，文档书写不够直观的问题。后来发现，这个小功能还有很多应用场景。我会在接下来的时间，安排对插件升级一下。

**Comment by meiMingle** [comment]
> @shaochangxing 由于最早的设计目的是解决项目交接的时候，文档书写不够直观的问题。后来发现，这个小功能还有很多应用场景。我会在接下来的时间，安排对插件升级一下。

现在支持了吗?大佬.好想要这个功能啊

**Comment by Link-Kou** [comment]
这段时间，我安排时间，把此功能加上去

**Comment by Link-Kou** [comment]
@shaochangxing  @meiMingle 
2.0.0发布了，支持右键菜单添加备注。
此版本基本上已经测试完成。初步已稳定性

**Comment by shaochangxing** [comment]
@Link-Kou 装了2.0之后功能失效了,右键添加的备注路径是系统绝对路径，改成相对路径后也不行。
版本是最新的IDEA IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021
```
<?xml version="1.0" encoding="UTF-8"?>
<trees>
    <tree path="/_web" title="手动添加"/>
    <tree path="D:\Research\techv_energy\_web" title="右键添加"/>
</trees>
```

**Comment by Link-Kou** [comment]
先等等，目前就在mac下面进行了测试。win的还在测试。明天或后天，发布到商城中去

**Comment by Link-Kou** [comment]
我测试了win的没有问题 @shaochangxing  你的情况可以录屏截屏给我看一下吗？

**Comment by shaochangxing** [comment]
***@***.***
 
发件人： Link-Kou
发送时间： 2021-06-10 16:07
收件人： Link-Kou/intellij-treeInfotip
抄送： 胃在烧; Mention
主题： Re: [Link-Kou/intellij-treeInfotip] 能否直接在文件夹或文件右键添加备注呢？ (#1)
我测试了win的没有问题 @shaochangxing 你的情况可以录屏截屏给我看一下吗？

**Comment by Link-Kou** [comment]
@shaochangxing  你先卸载插件后，重新安装。尝试一下。
你给我一下你的IDEA的版本，我在你的版本下，在测试一下

**Comment by shaochangxing** [comment]
@Link-Kou 
卸载重装了也不行，我用的是最新版本的。
IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021
Licensed to Ai Shao gu
Subscription is active until June 22, 2021.
For educational use only.
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1898M
Cores: 6
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: com.linkkou.plugin.intellij.assistant (2.0.0), de.netnexus.camelcaseplugin (3.0.8), org.jetbrains.plugins.vue (211.7142.13), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), cn.wuzhizhan.plugin.mybatis (2020.12.18)
Kotlin: 211-1.5.10-release-891-IJ7142.45

**Comment by Link-Kou** [comment]
@shaochangxing 
截图 一下 ，弹出框中的路径是否与文件中记录的一致。让我能判断一下
![image](https://user-images.githubusercontent.com/22113151/122005946-d257ac80-cde8-11eb-8146-26f28b0952a8.png)

**Comment by weizhiwen** [comment]
![Uploading image.png…]()

**Comment by weizhiwen** [comment]
![image](https://user-images.githubusercontent.com/22706559/122141518-16e25700-ce80-11eb-8736-088795e108f2.png)

**Comment by shaochangxing** [comment]
@Link-Kou 是一致的
![2](https://user-images.githubusercontent.com/11647361/122142461-1f3b9180-ce82-11eb-83af-3d1f116dbea4.png)

**Comment by shaochangxing** [comment]
@Link-Kou 报了个错
![3](https://user-images.githubusercontent.com/11647361/122142965-054e7e80-ce83-11eb-9b2a-47c897c40d9c.png)

**Comment by shaochangxing** [comment]
@Link-Kou 更新了之后可以显示了，谢谢！可以把这个插件推荐给其他同事了。
