### ISSUE TITLE
可以增加其它IDE如Goland，PhpStorm的适配吗

### ISSUE THREAD

**Issue by Wilson-Edwards** [Link-Kou/intellij-treeInfotip#10]

**Comment by Link-Kou** [comment]
@Wilson-Edwards  可以的。我安排时间适配一下

**Comment by sdtime-io** [comment]
亲测有效：将插件下载到本地后，打开goland、PhpStorm 等其他编辑器，点击从本地安装插件，可以直接安装此插件，并且运行正常。

**Comment by feng99** [comment]
> 亲测有效：将插件下载到本地后，打开goland、PhpStorm 等其他编辑器，点击从本地安装插件，可以直接安装此插件，并且运行正常。
感谢作者的插件.
感谢你的这条评论
解决了我的问题
