### ISSUE TITLE
2

### ISSUE THREAD

**Issue by liubin-1** [Link-Kou/intellij-treeInfotip#12]

**Comment by liubin-1** [comment]
2018版本的 idea安装该插件1.0.2版本，不生效

**Comment by Link-Kou** [comment]
@liubin-1 是的2018版本有些低了建议升级到2020以上版本

**Comment by liubin-1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liubin-1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
