### ISSUE TITLE
复杂项目似乎无法显示右键菜单

### ISSUE THREAD

**Issue by beansoft** [Link-Kou/intellij-treeInfotip#13]
我打开的是IDEA 2022.2的源码 项目巨复杂 然后点右键找不到菜单项

**Comment by Link-Kou** [comment]
@beansoft  这个有些意思，我也下载试一下看看

**Comment by Link-Kou** [comment]
发现这个是跟电脑性能有很大的关系

**Comment by beansoft** [comment]
我大概了解了，你的代码：https://github.com/Link-Kou/intellij-treeInfotip/blob/master/src/main/java/com/plugins/infotip/ActionDescriptionText.java

不是Dumbaware的，必须等项目索引完才能显示，建议你加入下列代码：

```java
    // Always available and enabled
    @Override
    public boolean isDumbAware() {
        return true;
    }
```
否则大项目将过很久才能看到菜单项。
