### ISSUE TITLE
[建议]能否添加一个单独的窗口

### ISSUE THREAD

**Issue by TankCoder** [Link-Kou/intellij-treeInfotip#16]
因为只会给部分文件添加说明，但是有时候找不到这个文件了，如果有一个类似bookmark的窗口，应该会更好用一点？

在没有用这个插件之前，我使用的就是书签，虽然功能看似一样，但是还是有所区别的，书签会更细致一些。

**Comment by Link-Kou** [comment]
@TankCoder 近期会优化

**Comment by Link-Kou** [comment]
@TankCoder 功能已经支持了
