### ISSUE TITLE
大佬有没有做过给webstrom 右下角git远程分支名称加备注的插件呀

### ISSUE THREAD

**Issue by gjynb** [Link-Kou/intellij-treeInfotip#18]
大佬有没有做过给webstrom 右下角git远程分支名称加备注的插件呀，苦苦无处寻觅，大佬给文件加备注的插件是我梦寐以求某次网上冲浪偶然发现，用了很久很是舒服，感恩大佬，
最近因为上线内容堆积导致git管理比较麻烦分支名称混乱有时候不太清楚哪个分支是何时上线，所以过来问问大佬是否做过这种插件。

**Comment by Link-Kou** [comment]
@gjynb 

你说的问题属于QA范围，分支的管理通常是有一定标准的。
master 永远是上线用的分支，上线后的master要打一个tag
其他的分支一般用日期作为命名居多。表示要开发任务的周期，每次合并到master后就要将此分支保护起来。
这个过程一般需要使用 专业的 ci/cd（持续交付工具），过程中也要有交付件等配合

如果团队毕竟少，建议通过约定成俗的方式进行。

**Comment by gjynb** [comment]
@Link-Kou 感谢大佬的回复，因为我们项目的特殊性，以至于经常有一些外力作用导致更新延期，使得原本命名为7月***的更新分支，延期到了8月，并且我们开发模式是分需求开发，导致我们本地更新前会存留很多不同需求的开发分支，经常会遇到7月的几个分支延期到8月更新，这样根据上线日期命名就显得更加混乱，现在我们只能通过笔记的方式把分支去做一个记录，以免更新时上传了不该上传的分支

**Comment by Link-Kou** [comment]
@gjynb 

你说的问题，其实我所在的厂子也是有的。
不过你说的需要一个工具也是合理的毕竟在IDEA内统一管理总是比较方便，不过我建议通过在线协作工具做管理会更好一些，QA类的管理应用确实是不多见。

有几个场景跟你也分享一下：

1、不同的分支开发，会碰到一个功能点会被多个需求波及，更坑爹的是还是多个开发人员同时开发的。
此问题说实在的涉及到的就是管理问题和任务分配的问题，团队内要及时沟通，甚至于要调整工作任务。

2、需求被延期或更新如何管理上线问题

中等团队都会有一个产品经理兼职QA做版本功能的管理，或者有单独的QA做这个事情，都没有的情况就是团队内找个其他人兼职着。

3、多个分支版本如何局部合并到Master上面。

看一下 git cherry-pick 命令，完美解决你的问题，不过对于团队git规范也是一个不小的挑战。

4、多任务开发是否创建多个分支

我的回答是的，不同的任务一定在不同的分支上。注意这里不是功能，功能会有多模块波及的场景。而任务是单一的。
团队内要用好ISSUES，在git提交中用‘#100’的方式标记，可以直接在ISSUES中关联到具体的分支上，也是一种解决管理的办法

**Comment by gjynb** [comment]
@Link-Kou 谢谢大佬的分享，这些场景真的不止一次出现在我们的版本迭代中一直困扰我们，明明基本是一样的需求两个产品做了两套分给了不同的两个前端开发两个后端开发，开发完和代码一堆冲突，提交到测试岗后因为两个需求内容有很多交集改动导致他们案例都不知道该怎么写，还有由于管理部门的要求我们更新频率可以说算是很低，基本一个月或者推迟两个月更新一次，堆积需求问题很频繁，大佬也遇到类似问题看来这些问题是每一个产品与开发之间的通病了，有时候提出问题反倒惹得产品反感，不提出自己就要被恶心，我们项目组三个产品现在我估计已经进两个产品的黑名单了，哈哈哈哈哈哈
