### ISSUE TITLE
idea 2021.1.2 (211.7442.40) 无法使用 

### ISSUE THREAD

**Issue by Hisensun** [Link-Kou/intellij-treeInfotip#4]
![image](https://user-images.githubusercontent.com/47417466/121621548-ef197a80-ca9e-11eb-85c9-4152d5f20136.png)
![image](https://user-images.githubusercontent.com/47417466/121622100-f8571700-ca9f-11eb-936e-57fe01ecc9ca.png)

版本如图 应该是最最新版 （正版）新建xml 然后右键进行标记 xml中已生成数据 但文件树未出现标识

**Comment by Link-Kou** [comment]
@Hisensun 
截图 一下 ，弹出框中的路径是否与文件中记录的一致。让我能判断一下 
![image](https://user-images.githubusercontent.com/22113151/122005191-e8b13880-cde7-11eb-9050-da398825b359.png)

**Comment by weizhiwen** [comment]
![image](https://user-images.githubusercontent.com/22706559/122045727-a9e3a880-ce10-11eb-9113-1f610f90c03f.png)

**Comment by weizhiwen** [comment]
我也出现了这个问题

**Comment by Link-Kou** [comment]
@weizhiwen  @Hisensun   麻烦在测试一下 此版本  https://github.com/Link-Kou/intellij-treeInfotip/releases/tag/2.0.1

**Comment by Hisensun** [comment]
![image](https://user-images.githubusercontent.com/47417466/122147134-de944600-ce8a-11eb-8c88-d62b16a2407e.png)
好像还是不行

**Comment by Hisensun** [comment]
![image](https://user-images.githubusercontent.com/47417466/122147202-04b9e600-ce8b-11eb-8fae-b90d52e3b4da.png)
路径已经是相对路径了

**Comment by Link-Kou** [comment]
@Hisensun  嗯嗯，看一下是否可以正常显示目录书备注了

**Comment by Hisensun** [comment]
不行 你看看我上一张图 我发了两张

**Comment by Link-Kou** [comment]
@Hisensun  把DirectoryV2.xml删除，右键目录添加菜单，插件会自己重新创建XML

**Comment by Hisensun** [comment]
![image](https://user-images.githubusercontent.com/47417466/122148433-1603f200-ce8d-11eb-8e0c-54f1fc6b7670.png)
![image](https://user-images.githubusercontent.com/47417466/122148441-18fee280-ce8d-11eb-8249-b52f4c212422.png)
还是不行

**Comment by Hisensun** [comment]
你下一个 最新版试试呢

![image](https://user-images.githubusercontent.com/47417466/122148587-4c417180-ce8d-11eb-90df-e6e5a608376d.png)

**Comment by weizhiwen** [comment]
Details: Current thread: Thread[Thread-6,6,Idea Thread Group] 1010544980
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1239297019

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:717)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:237)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:342)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:311)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:216)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:185)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:84)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:71)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:139)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:62)
	at com.plugins.infotip.FileDirectory.getFileDirectoryXml(FileDirectory.java:40)
	at com.plugins.infotip.XmlParsing$4.run(XmlParsing.java:158)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by weizhiwen** [comment]
![image](https://user-images.githubusercontent.com/22706559/122154493-b7904100-ce97-11eb-9cc5-5a0965e31239.png)

**Comment by weizhiwen** [comment]
![image](https://user-images.githubusercontent.com/22706559/122154518-c37c0300-ce97-11eb-92a1-984b36f84565.png)

**Comment by weizhiwen** [comment]
最新版也还是有问题，路径在Windows下是有问题的
![image](https://user-images.githubusercontent.com/22706559/122154566-dabaf080-ce97-11eb-9ad1-02199ed0a018.png)

**Comment by weizhiwen** [comment]
已经把你代码clone下来了，还没来得及找问题改呢，哈哈哈

**Comment by Link-Kou** [comment]
已经更新了一个版本了，修复了问题，请各位测试看看，有问题在提提建议
https://github.com/Link-Kou/intellij-treeInfotip/releases/tag/2.1.0

**Comment by Hisensun** [comment]
新版本的问题修复了 吗 大神

**Comment by Hisensun** [comment]
新版本的问题修复了 吗 大神

**Comment by weizhiwen** [comment]
2.1.0版本我在Windows电脑使用还是不行，路径还是有问题

**Comment by weizhiwen** [comment]
![image](https://user-images.githubusercontent.com/22706559/122219088-abc96c80-cee1-11eb-8803-85b981741a9f.png)

**Comment by Link-Kou** [comment]
今天又又又发布了一个版本,各位在测试
https://github.com/Link-Kou/intellij-treeInfotip/releases/tag/2.1.0

**Comment by weizhiwen** [comment]
哈哈哈，还是不行，我帮你修复吧，我用的windows电脑，你那边用Mac不好搞

**Comment by Link-Kou** [comment]
搭建了虚拟机测试一遍。现在解决掉了，我这里测试没有问题了 @weizhiwen 试下

**Comment by weizhiwen** [comment]
我这边可以了 @Link-Kou  👍 
![image](https://user-images.githubusercontent.com/22706559/122489362-18dc1f80-d012-11eb-885d-8ff1f4c208bd.png)

**Comment by Hisensun** [comment]
![image](https://user-images.githubusercontent.com/47417466/122489791-09a9a180-d013-11eb-9359-4691e977ce6c.png)
好用了 厉害
