### ISSUE TITLE
备注信息消失 的问题

### ISSUE THREAD

**Issue by Hisensun** [Link-Kou/intellij-treeInfotip#6]
录入备注后  每次目录有所改动（刷新）备注信息会消失 点击消失的备注项后 再点击别的项就会出现 有点类似刮刮乐

**Comment by Link-Kou** [comment]
@Hisensun  在Windows的平台上出现此情况，我还在验证中。mac平台下没有。

**Comment by Hisensun** [comment]
我录制了动画 你看一下 idea 版本没有变化 还是上次哪个版本 
![动画bug](https://user-images.githubusercontent.com/47417466/122500852-24d1dc80-d026-11eb-9e8d-9c0cb3dd7cc3.gif)

**Comment by Link-Kou** [comment]
@Hisensun  试试看  https://github.com/Link-Kou/intellij-treeInfotip/releases/tag/2.1.1

**Comment by Hisensun** [comment]
我测了 没什么问题了 可用 问题可以关闭了
