### ISSUE TITLE
安装插件后打开任何窗口关闭都会变灰

### ISSUE THREAD

**Issue by MaoSource** [Link-Kou/intellij-treeInfotip#9]
随便打开一个窗口关闭就这样了
![A43U})Q02W6POG4V5$)IP`K](https://user-images.githubusercontent.com/56857029/154006953-745f54d8-3eb6-47d5-afa0-b94e35a30eb3.png)
正常情况应该是这样的
![P{~L@O X243S}Q2)2TK3EV6](https://user-images.githubusercontent.com/56857029/154006988-c5ffdd0c-0d81-42dd-b8a4-31f50a2e36e2.png)

**Comment by Link-Kou** [comment]
@MaoSource  你的IDEA的版本是多少的？

**Comment by MaoSource** [comment]
> @MaoSource 你的IDEA的版本是多少的？

![image](https://user-images.githubusercontent.com/56857029/154398464-5bc8e292-56ac-4875-a229-96b4c4870070.png)
2021.2.2
